# Generated by Django 4.2.1 on 2023-05-26 15:36

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image logo')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('part-time', 'part-time'), ('remote', 'remote'), ('contract', 'contract'), ('negotiation', 'negotiation')], default='negotiation', max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('Senior', 'Senior'), ('Junior', 'Junior'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Senior', max_length=200)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2023, 5, 26, 15, 36, 43, 38916, tzinfo=datetime.timezone.utc))),
                ('auther', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='C_H_App.employer_model')),
            ],
        ),
    ]
