# Generated by Django 4.2.1 on 2023-05-26 14:16

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('C_H_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image logo')),
            ],
        ),
        migrations.RemoveField(
            model_name='job_model',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job_model',
            name='time',
        ),
        migrations.AddField(
            model_name='job_model',
            name='auther',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job_model',
            name='contract_type',
            field=models.CharField(choices=[('part-time', 'part-time'), ('remote', 'remote'), ('contract', 'contract'), ('negotiation', 'negotiation')], default='negotiation', max_length=200),
        ),
        migrations.AddField(
            model_name='job_model',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2023, 5, 26, 14, 16, 16, 685338, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='job_model',
            name='level',
            field=models.CharField(choices=[('Senior', 'Senior'), ('Junior', 'Junior'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Senior', max_length=200),
        ),
        migrations.AlterField(
            model_name='job_model',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Company_Model',
        ),
        migrations.AddField(
            model_name='job_model',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='C_H_App.employer_model'),
        ),
    ]
