# Generated by Django 4.2.1 on 2023-05-26 14:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('C_H_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_model',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image logo'),
        ),
    ]
