# Generated by Django 4.2.1 on 2023-05-26 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_H_App', '0002_employer_model_remove_job_model_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_model',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2023, 5, 26, 14, 37, 56, 344315, tzinfo=datetime.timezone.utc)),
        ),
    ]
