# Generated by Django 4.2.1 on 2023-05-26 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_H_App', '0002_alter_job_model_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_model',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2023, 5, 26, 15, 50, 26, 670007, tzinfo=datetime.timezone.utc)),
        ),
    ]
