# Generated by Django 4.2.1 on 2023-05-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Applicant',
            new_name='is_applicant',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_Employer',
            new_name='is_employer',
        ),
    ]
